# Example Site settings

#google_analytics: UA-NNNNNNNN-N


header_pages:
  - home.md
  - Articles.md
  - Writeups.md
  - about.md

  #- info.md



footer: 
- 'Follow me on <a href="https://twitter.com/L0rd5ud0">Twitter</a> <br/> <br/> Â©2023 Lord Sudo, All rights Reserved' 



style: hacker
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
